import {
  BlogPost,
  FeaturedPost,
} from "@/app/(dashboard)/blog/_types/blog.types";

export const featuredPosts: FeaturedPost[] = [
  {
    id: 1,
    date: "08 Nov 2023",
    title: "Whiteboard Templates By Industry Leaders",
    coverImage: "/assets/images/cover/cover-1.webp",
    avatar: "/assets/images/avatar/avatar-1.webp",
    comments: "7.98k",
    views: "8.83k",
    shares: "8.56k",
    isLarge: true,
  },
  {
    id: 2,
    date: "09 Apr 2024",
    title: "Tesla Cybertruck-inspired camper trail...",
    coverImage: "/assets/images/cover/cover-2.webp",
    avatar: "/assets/images/avatar/avatar-2.webp",
    comments: "7.98k",
    views: "8.83k",
    shares: "8.56k",
    isLarge: false,
  },
  {
    id: 3,
    date: "12 Sep 2023",
    title: "Designify Agency Landing Page Design",
    coverImage: "/assets/images/cover/cover-3.webp",
    avatar: "/assets/images/avatar/avatar-3.webp",
    comments: "7.98k",
    views: "8.83k",
    shares: "8.56k",
    isLarge: false,
  },
];

export const blogPosts: BlogPost[] = [
  {
    id: 4,
    coverImage: "/assets/images/cover/cover-4.webp",
    title: "✨What is Done is Done ✨",
    avatar: "/assets/images/avatar/avatar-4.webp",
    date: "01 Jan 2024",
    comments: "7.98k",
    views: "8.83k",
    shares: "8.56k",
  },
  {
    id: 5,
    date: "23 Apr 2024",
    title: "Fresh Prince",
    coverImage: "/assets/images/cover/cover-5.webp",
    avatar: "/assets/images/avatar/avatar-5.webp",
    comments: "7.98k",
    views: "8.83k",
    shares: "8.56k",
  },
  {
    id: 6,
    date: "29 Feb 2024",
    title: "Six Socks Studio",
    coverImage: "/assets/images/cover/cover-6.webp",
    avatar: "/assets/images/avatar/avatar-6.webp",
    comments: "7.98k",
    views: "8.83k",
    shares: "8.56k",
  },
  {
    id: 7,
    date: "14 May 2024",
    title: "vincenzo de cotiis’ crossing over...",
    coverImage: "/assets/images/cover/cover-7.webp",
    avatar: "/assets/images/avatar/avatar-7.webp",
    comments: "7.98k",
    views: "8.83k",
    shares: "8.56k",
  },
  {
    id: 8,
    date: "13 Jan 2024",
    title: "Simple, Great Looking Animations in Your Project | Video Tutorial",
    coverImage: "/assets/images/cover/cover-8.webp",
    avatar: "/assets/images/avatar/avatar-8.webp",
    comments: "7.98k",
    views: "8.83k",
    shares: "8.56k",
  },
  {
    id: 9,
    date: "22 Jun 2024",
    title: "40 Free Serif Fonts for Digital Designers",
    coverImage: "/assets/images/cover/cover-9.webp",
    avatar: "/assets/images/avatar/avatar-9.webp",
    comments: "7.98k",
    views: "8.83k",
    shares: "8.56k",
  },
  {
    id: 10,
    date: "05 Oct 2023",
    title: "Examining the Evolution of the Typical Web Design Client",
    coverImage: "/assets/images/cover/cover-10.webp",
    avatar: "/assets/images/avatar/avatar-10.webp",
    comments: "7.98k",
    views: "8.83k",
    shares: "8.56k",
  },
  {
    id: 11,
    date: "11 Jul 2024",
    title: "Katie Griffin loves making that homey art",
    coverImage: "/assets/images/cover/cover-11.webp",
    avatar: "/assets/images/avatar/avatar-11.webp",
    comments: "7.98k",
    views: "8.83k",
    shares: "8.56k",
  },
  {
    id: 12,
    date: "22 May 2024",
    title: "The American Dream retold through mid-century railroad graphics",
    coverImage: "/assets/images/cover/cover-12.webp",
    avatar: "/assets/images/avatar/avatar-12.webp",
    comments: "7.98k",
    views: "8.83k",
    shares: "8.56k",
  },
  {
    id: 13,
    date: "29 Mar 2024",
    title: "Illustration System Design",
    coverImage: "/assets/images/cover/cover-13.webp",
    avatar: "/assets/images/avatar/avatar-13.webp",
    comments: "7.98k",
    views: "8.83k",
    shares: "8.56k",
  },
  {
    id: 14,
    date: "29 Aug 2023",
    title: "CarZio-Delivery Driver App SignIn/SignUp",
    coverImage: "/assets/images/cover/cover-14.webp",
    avatar: "/assets/images/avatar/avatar-14.webp",
    comments: "7.98k",
    views: "8.83k",
    shares: "8.56k",
  },
  {
    id: 15,
    date: "19 Nov 2023",
    title:
      "How to create a client-serverless Jamstack app using Netlify, Gatsby and Fauna",
    coverImage: "/assets/images/cover/cover-15.webp",
    avatar: "/assets/images/avatar/avatar-15.webp",
    comments: "7.98k",
    views: "8.83k",
    shares: "8.56k",
  },
  {
    id: 16,
    date: "24 Oct 2023",
    title: "Tylko Organise effortlessly -3D & Motion Design",
    coverImage: "/assets/images/cover/cover-16.webp",
    avatar: "/assets/images/avatar/avatar-16.webp",
    comments: "7.98k",
    views: "8.83k",
    shares: "8.56k",
  },
  {
    id: 17,
    date: "02 Dec 2023",
    title: "RAYO ?? A expanded visual arts festival identity",
    coverImage: "/assets/images/cover/cover-17.webp",
    avatar: "/assets/images/avatar/avatar-17.webp",
    comments: "7.98k",
    views: "8.83k",
    shares: "8.56k",
  },
  {
    id: 18,
    date: "13 Feb 2024",
    title:
      "Anthony Burrill and Wired mag’s Andrew Diprose discuss how they made January’s Change Everything cover",
    coverImage: "/assets/images/cover/cover-18.webp",
    avatar: "/assets/images/avatar/avatar-18.webp",
    comments: "7.98k",
    views: "8.83k",
    shares: "8.56k",
  },
  {
    id: 19,
    date: "19 Sep 2023",
    title: "Inside the Mind of Samuel Day",
    coverImage: "/assets/images/cover/cover-19.webp",
    avatar: "/assets/images/avatar/avatar-19.webp",
    comments: "7.98k",
    views: "8.83k",
    shares: "8.56k",
  },
  {
    id: 20,
    date: "17 Apr 2024",
    title: "Portfolio Review: Is This Portfolio Too Creative?",
    coverImage: "/assets/images/cover/cover-20.webp",
    avatar: "/assets/images/avatar/avatar-20.webp",
    comments: "7.98k",
    views: "8.83k",
    shares: "8.56k",
  },
  {
    id: 21,
    date: "18 Dec 2023",
    title: "Akkers van Margraten",
    coverImage: "/assets/images/cover/cover-21.webp",
    avatar: "/assets/images/avatar/avatar-21.webp",
    comments: "7.98k",
    views: "8.83k",
    shares: "8.56k",
  },
  {
    id: 22,
    date: "27 Jun 2024",
    title: "Gradient Ticket icon",
    coverImage: "/assets/images/cover/cover-22.webp",
    avatar: "/assets/images/avatar/avatar-22.webp",
    comments: "7.98k",
    views: "8.83k",
    shares: "8.56k",
  },
  {
    id: 23,
    date: "19 Oct 2023",
    title: "Here’s a Dyson motorcycle concept that doesn’t ‘suck’!",
    coverImage: "/assets/images/cover/cover-23.webp",
    avatar: "/assets/images/avatar/avatar-23.webp",
    comments: "7.98k",
    views: "8.83k",
    shares: "8.56k",
  },
];
