import { Product } from "@/app/(dashboard)/product/_types/product.types";

export const PRODUCTS_DATA: Product[] = [
  {
    id: 1,
    title: "Nike Air Force 1 NDESTRUKT",
    image: "/assets/images/product/product-1.webp",
    price: 35.17,
    status: "sale",
    colors: ["#00A76F", "#000000"],
    numberOfColors: false,
  },
  {
    id: 2,
    title: "Nike Space Hippie 04",
    image: "/assets/images/product/product-2.webp",
    price: 57.22,
    status: null,
    colors: ["#000000", "#FFFFFF"],
    numberOfColors: false,
  },
  {
    id: 3,
    title: "Nike Air Zoom Pegasus 37 A.I.R. Chaz Bear",
    image: "/assets/images/product/product-3.webp",
    price: 64.78,
    status: "sale",
    colors: ["#ffc0cb", "#FFFFFF"],
    numberOfColors: false,
  },
  {
    id: 4,
    title: "Nike Blazer Low 77 Vintage",
    image: "/assets/images/product/product-4.webp",
    price: 50.79,
    status: "new",
    colors: ["#ffc0cb", "#FF5630", "#00B8D9"],
    numberOfColors: false,
  },
  {
    id: 5,
    title: "Nike ZoomX SuperRep Surge",
    image: "/assets/images/product/product-5.webp",
    price: 9.57,
    status: "sale",
    colors: ["#00A76F", "#000000", "#FFFFFF"],
    numberOfColors: true,
  },
  {
    id: 6,
    title: "Zoom Freak 2",
    image: "/assets/images/product/product-6.webp",
    price: 61.46,
    status: null,
    colors: ["#00A76F", "#000000", "#FFFFFF"],
    numberOfColors: true,
  },
  {
    id: 7,
    title: "Nike Air Max Zephyr",
    image: "/assets/images/product/product-7.webp",
    price: 96.73,
    status: null,
    colors: ["#00A76F", "#000000", "#FFFFFF"],
    numberOfColors: true,
  },
  {
    id: 8,
    title: "Jordan Delta",
    image: "/assets/images/product/product-8.webp",
    price: 63.04,
    status: "new",
    colors: ["#00A76F", "#000000", "#FFFFFF"],
    numberOfColors: true,
  },
  {
    id: 9,
    title: "Air Jordan XXXV PF",
    image: "/assets/images/product/product-9.webp",
    price: 33.18,
    status: null,
    colors: ["#00A76F", "#000000", "#FFFFFF"],
    numberOfColors: true,
  },
  {
    id: 10,
    title: "Nike Waffle Racer Crater",
    image: "/assets/images/product/product-10.webp",
    price: 36.3,
    status: null,
    colors: ["#00A76F", "#000000", "#FFFFFF"],
    numberOfColors: true,
  },
  {
    id: 11,
    title: "Kyrie 7 EP Sisterhood",
    image: "/assets/images/product/product-11.webp",
    price: 54.42,
    status: null,
    colors: ["#00A76F", "#000000", "#FFFFFF"],
    numberOfColors: true,
  },
  {
    id: 12,
    title: "Nike Air Zoom BB NXT",
    image: "/assets/images/product/product-12.webp",
    price: 20.52,
    status: "new",
    colors: ["#00A76F", "#000000", "#FFFFFF"],
    numberOfColors: true,
  },

  {
    id: 13,
    title: "Nike Air Force 1 07 LX",
    image: "/assets/images/product/product-13.webp",
    price: 62.82,
    status: null,
    colors: ["#00A76F", "#000000", "#FFFFFF"],
    numberOfColors: true,
  },
  {
    id: 14,
    title: "Nike Air Force 1 Shadow SE",
    image: "/assets/images/product/product-14.webp",
    price: 19.96,
    status: null,
    colors: ["#00A76F", "#000000", "#FFFFFF"],
    numberOfColors: true,
  },
  {
    id: 15,
    title: "Nike Air Zoom Tempo NEXT%",
    image: "/assets/images/product/product-15.webp",
    price: 25.93,
    status: null,
    colors: ["#00A76F", "#000000", "#FFFFFF"],
    numberOfColors: true,
  },
  {
    id: 16,
    title: "Nike DBreak-Type",
    image: "/assets/images/product/product-16.webp",
    price: 70.39,
    status: null,
    colors: ["#00A76F", "#000000", "#FFFFFF"],
    numberOfColors: true,
  },
  {
    id: 17,
    title: "Nike Air Max Up",
    image: "/assets/images/product/product-17.webp",
    price: 23.11,
    status: null,
    colors: ["#00A76F", "#000000", "#FFFFFF"],
    numberOfColors: true,
  },
  {
    id: 18,
    title: "Nike Air Max 270 React ENG",
    image: "/assets/images/product/product-18.webp",
    price: 67.23,
    status: null,
    colors: ["#00A76F", "#000000", "#FFFFFF"],
    numberOfColors: true,
  },
  {
    id: 19,
    title: "NikeCourt Royale",
    image: "/assets/images/product/product-19.webp",
    price: 14.31,
    status: null,
    colors: ["#00A76F", "#000000", "#FFFFFF"],
    numberOfColors: true,
  },
  {
    id: 20,
    title: "Nike Air Zoom Pegasus 37 Premium",
    image: "/assets/images/product/product-20.webp",
    price: 31.5,
    status: null,
    colors: ["#00A76F", "#000000", "#FFFFFF"],
    numberOfColors: true,
  },

  {
    id: 21,
    title: "Nike Air Zoom SuperRep",
    image: "/assets/images/product/product-21.webp",
    price: 26.72,
    status: null,
    colors: ["#00A76F", "#000000", "#FFFFFF"],
    numberOfColors: true,
  },
  {
    id: 22,
    title: "NikeCourt Royale",
    image: "/assets/images/product/product-22.webp",
    price: 44.8,
    status: null,
    colors: ["#00A76F", "#000000", "#FFFFFF"],
    numberOfColors: true,
  },
  {
    id: 23,
    title: "Nike React Art3mis",
    image: "/assets/images/product/product-23.webp",
    price: 37.87,
    status: null,
    colors: ["#FF5630", "#00B8D9"],
    numberOfColors: false,
  },
  {
    id: 24,
    title: "Nike React Infinity Run Flyknit A.I.R. Chaz Bear",
    image: "/assets/images/product/product-24.webp",
    price: 75.53,
    status: null,
    colors: ["#00B8D9"],
    numberOfColors: false,
  },
];
