import { User } from "@/app/(dashboard)/user/_types/users.types";
export const USERS_DATA: User[] = [
  {
    id: 1,
    name: "Adam Trantow",
    avatar: "/assets/images/avatar/avatar-22.webp",
    company: "Mohr, Langworth and Hills",
    role: "UI Designer",
    verified: true,
    status: "Active",
  },
  {
    id: 2,
    name: "Angel Rolfson-Kulas",
    avatar: "/assets/images/avatar/avatar-18.webp",
    company: "Koch and Sons",
    role: "UI Designer",
    verified: true,
    status: "Active",
  },
  {
    id: 3,
    name: "Betty Hammes",
    avatar: "/assets/images/avatar/avatar-15.webp",
    company: "Waelchi - VonRueden",
    role: "UI Designer",
    verified: true,
    status: "Active",
  },
  {
    id: 4,
    name: "Billy Braun",
    avatar: "/assets/images/avatar/avatar-21.webp",
    company: "White, Cassin and Goldner",
    role: "UI Designer",
    verified: false,
    status: "Banned",
  },
  {
    id: 5,
    name: "Billy Stoltenberg",
    avatar: "/assets/images/avatar/avatar-1.webp",
    company: "Medhurst, Moore and Franey",
    role: "Leader",
    verified: true,
    status: "Banned",
  },
  {
    id: 6,
    name: "Brandon Von",
    avatar: "/assets/images/avatar/avatar-23.webp",
    company: "Mitchell, Volkman and Prosacco",
    role: "UI Designer",
    verified: true,
    status: "Active",
  },
  {
    id: 7,
    name: "Brian Jacobs",
    avatar: "/assets/images/avatar/avatar-10.webp",
    company: "Howe - Anderson",
    role: "Full Stack Developer",
    verified: true,
    status: "Active",
  },
  {
    id: 8,
    name: "Charlene Krajcik",
    avatar: "/assets/images/avatar/avatar-13.webp",
    company: "Schmidt LLC",
    role: "UI Designer",
    verified: true,
    status: "Banned",
  },
  {
    id: 9,
    name: "Cheryl Romaguera",
    avatar: "/assets/images/avatar/avatar-20.webp",
    company: "Weimann LLC",
    role: "UI Designer",
    verified: false,
    status: "Active",
  },
  {
    id: 10,
    name: "Dr. Guadalupe Rath",
    avatar: "/assets/images/avatar/avatar-5.webp",
    company: "Spencer, Raynor and Langosh",
    role: "UI/UX Designer",
    verified: true,
    status: "Banned",
  },
  {
    id: 11,
    name: "Dr. Lee Doyle-Grant",
    avatar: "/assets/images/avatar/avatar-19.webp",
    company: "Klein - Rolfson",
    role: "UI Designer",
    verified: false,
    status: "Active",
  },
  {
    id: 12,
    name: "Eloise Ebert",
    avatar: "/assets/images/avatar/avatar-2.webp",
    company: "Hahn, Homenick and Lind",
    role: "Hr Manager",
    verified: false,
    status: "Active",
  },
  {
    id: 13,
    name: "Kelvin Pouros",
    avatar: "/assets/images/avatar/avatar-6.webp",
    company: "Lehner - Feeney",
    role: "Project Manager",
    verified: true,
    status: "Active",
  },
  {
    id: 14,
    name: "Kerry Kuhlman",
    avatar: "/assets/images/avatar/avatar-14.webp",
    company: "Smitham - Gerlach",
    role: "UI Designer",
    verified: false,
    status: "Active",
  },
  {
    id: 15,
    name: "Kristen Wunsch",
    avatar: "/assets/images/avatar/avatar-8.webp",
    company: "Gutmann - Kassulke",
    role: "Full Stack Designer",
    verified: false,
    status: "Active",
  },
  {
    id: 16,
    name: "Lillie Schultz",
    avatar: "/assets/images/avatar/avatar-11.webp",
    company: "Sipes - Yost",
    role: "UI Designer",
    verified: false,
    status: "Active",
  },
  {
    id: 17,
    name: "Mr. Conrad Spinka",
    avatar: "/assets/images/avatar/avatar-12.webp",
    company: "Johns - Aufderhar",
    role: "UI Designer",
    verified: true,
    status: "Active",
  },
  {
    id: 18,
    name: "Salvador Mayert",
    avatar: "/assets/images/avatar/avatar-4.webp",
    company: "Stamm, Larson and Mertz",
    role: "UX Designer",
    verified: false,
    status: "Active",
  },
  {
    id: 19,
    name: "Sherri Davis",
    avatar: "/assets/images/avatar/avatar-17.webp",
    company: "Lemke - Ferry",
    role: "UI Designer",
    verified: false,
    status: "Banned",
  },
  {
    id: 20,
    name: "Steve Welch",
    avatar: "/assets/images/avatar/avatar-9.webp",
    company: "Turcotte - Runolfsson",
    role: "Front End Developer",
    verified: false,
    status: "Banned",
  },
  {
    id: 21,
    name: "Teresa Luettgen",
    avatar: "/assets/images/avatar/avatar-3.webp",
    company: "Larkin LLC",
    role: "UI Designer",
    verified: true,
    status: "Active",
  },
  {
    id: 22,
    name: "Thelma Langworth",
    avatar: "/assets/images/avatar/avatar-7.webp",
    company: "Leuschke, Harris and Kuhlman",
    role: "Backend Developer",
    verified: true,
    status: "Active",
  },
  {
    id: 23,
    name: "Tony Paucek PhD",
    avatar: "/assets/images/avatar/avatar-16.webp",
    company: "Padberg - Macejkovic",
    role: "UI Designer",
    verified: false,
    status: "Active",
  },
  {
    id: 24,
    name: "Willis Ankunding",
    avatar: "/assets/images/avatar/avatar-24.webp",
    company: "Streich Group",
    role: "UI Designer",
    verified: false,
    status: "Active",
  },
];
