import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Users - Minimal-UI",
  description: "Generated by create next app",
};

const usersPage = () => {
  return (
    <>
      <div>Users</div>
    </>
  );
};

export default usersPage;
